trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m unittest discover
      displayName: 'Run tests'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'AzureFunction'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: '<Your Azure Subscription>'
              appType: 'functionAppLinux'
              appName: '<Your Function App Name>'
              package: '$(System.DefaultWorkingDirectory)'
